CREATE TABLE ingredients
(
    id       INTEGER NOT NULL,
    name     VARCHAR(255),
    quantity INTEGER NOT NULL,
    unit     VARCHAR(255),
    CONSTRAINT pk_ingredients PRIMARY KEY (id)
);

CREATE TABLE recipes
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    instructions VARCHAR(255),
    prep_time    INTEGER                                  NOT NULL,
    servings     INTEGER                                  NOT NULL,
    CONSTRAINT pk_recipes PRIMARY KEY (id)
);

CREATE TABLE recipes_ingredients
(
    recipe_id      INTEGER NOT NULL,
    ingredients_id INTEGER NOT NULL
);

ALTER TABLE recipes_ingredients
    ADD CONSTRAINT uc_recipes_ingredients_ingredients UNIQUE (ingredients_id);

ALTER TABLE recipes_ingredients
    ADD CONSTRAINT fk_recing_on_ingredient FOREIGN KEY (ingredients_id) REFERENCES ingredients (id);

ALTER TABLE recipes_ingredients
    ADD CONSTRAINT fk_recing_on_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id);